### ISSUE TITLE
Move to using raw .bib files for publications page

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/oduwsdl.github.io#4]
https://github.com/oduwsdl/oduwsdl.github.io/blob/master/_bibtexs/ainsworth-a.html is an odd franken-file containing some surfaced metadata and the raw bibtex content embedded in HTML. This produces a large barrier of entry in terms of other WS-DLers submitting new entries via a PR. Can you utilize the native .bib format as raw file then extract the contents as needed by the build system as metadata?

Also, the bibtex field in the entries in the YAML at https://github.com/oduwsdl/oduwsdl.github.io/blob/master/_data/pubs.yml direct to an HTML file.

**Comment by machawk1** [comment]
Also, the bibtex field in the entries in the YAML at https://github.com/oduwsdl/oduwsdl.github.io/blob/master/_data/pubs.yml direct to an HTML file.

**Comment by N0taN3rd** [comment]
@machawk1 

> This produces a large barrier of entry in terms of other WS-DLers submitting new entries via a PR. Can you utilize the native .bib format as raw file then extract the contents as needed by the build system as metadata?

I can :arrow_down: 

> Also, the bibtex field in the entries in the YAML at https://github.com/oduwsdl/oduwsdl.github.io/blob/master/_data/pubs.yml direct to an HTML file.

This was an design choice
``_config.yml``
```yaml
collections:
  bibtexs:
    output: true
    permalink: /:collection/:name
```
Jekyll has this feature call '[collections](https://jekyllrb.com/docs/collections/)' which allows for 'collections' of things not pages or posts to be rendered.
Since the field output: true is set jekyll will generate actual html on deployment rather than dynamically (makes archiving our page easier :stuck_out_tongue_winking_eye:). 
The current manner by which they are stored does not need to change and how others add to this collection is flexible. 

### All bibtex pages could can be html or md but require this jekyll markup at the bare minimum
```md
---
layout: post
title: 'Impact of URI Canonicalization on Memento Count'
description: Mat Kelly, Lulwah M. Alkwai, Sawood Alam, Michael L. Nelson, Michele C. Weigle, and Herbert Van de Sompel
bib: kelly-c.bib
---
```
and then only include 
```html
<h1>kelly-countingMementos2017</h1>
<h3>Summary</h3>
<p>Mat Kelly, Lulwah M. Alkwai, Sawood Alam, Michael L. Nelson, Michele C. Weigle, and Herbert Van de Sompel, "Impact of URI Canonicalization on Memento Count," In <em>Proceedings of the 16th ACM/IEEE-CS Joint Conference on Digital Libraries</em>. June 2017, To Appear.
<a id="kelly-countingMementos2017Bib" name="kelly-countingMementos2017Bib"></a>
</p>
</div>
<h3>Bibtex entry</h3>
```
or 
```md
# bib-key
### Summary
<authors, name, where accepted/present text>
```
And the ``.bib`` file could be placed in a sub directory ``_bibtexs/bib`` or right beside the user created content and internally add a specific __layouts for BibTeX 

### Or bibtex pages are only .md
```md
---
layout: bibtex
title: 'Impact of URI Canonicalization on Memento Count'
description: Mat Kelly, Lulwah M. Alkwai, Sawood Alam, Michael L. Nelson, Michele C. Weigle, and Herbert Van de Sompel
bibKey: kelly-countingMementos2017
summary: Mat Kelly, Lulwah M. Alkwai, Sawood Alam, Michael L. Nelson, Michele C. Weigle, and Herbert Van de Sompel, "Impact of URI Canonicalization on Memento Count"
where:  In Proceedings of the 16th ACM/IEEE-CS Joint Conference on Digital Libraries
datetime: June 2017, To Appear
.....etc etc
---
@INPROCEEDINGS { kelly-countingMementos2017,
    AUTHOR = { Mat Kelly, Lulwah M. Alkwai, Sawood Alam, Michael L. Nelson, Michele C. Weigle, and Herbert Van de Sompel },
    TITLE = { Impact of URI Canonicalization on Memento Count },
    BOOKTITLE = { Proceedings of the 16th ACM/IEEE-CS Joint Conference on Digital Libraries },
    SERIES = { JCDL '17 },
    YEAR = { 2017 },
    MONTH = { jun },
    NOTE = { To Appear },
}
````  

If it is just the raw bibtex someone whould have to create a parser or run pre commit hooks to render the raw bibtex for us. 
Github pages does not allow plugins which would do this automatically.

**Comment by machawk1** [comment]
Everything between the '---' seems redundant and potentially inconsistent with the bibtex info below. A hook may be the way to go for the sake of interoperability.

**Comment by phonedude** [comment]
Closing this since we're moving away from manually maintained pub lists.
